# -*- coding: utf-8 -*-
"""Basics of Python Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4DMYMw9ShayjypODeznZuAQ0RSa3iXM

1. Prime Numbers
"""

n = int(input("Enter a number: "))
c = 0
for i in range(2, int(n/2)+1): #number in range from 2 to half of the n
    if n%i==0:
        c+=1
    break
if c==0 and n > 1:
    print(n, "is a prime number")
else:
    print(n, "is not a prime number")

"""2. Product of Random Numbers"""

pip install numpy

import numpy as np
import random

a=np.random.randint(1,100) #randam number 1
b=np.random.randint(1,100) #random number 2
print(a,b)
c=a*b          #product of random numbers
d=int(input("Enter the Product : "))
if d==c:
 print("Correct")
else:
 print("Incorrect")

"""3. Squares of Even/Odd Numbers"""

for i  in range (100, 200):
      if i%2==0:
        print (i**2)

"""Word Counter"""

word=input()    #string input
slist=word.split()  #splits the string and saves in the list
for i in slist:
    print(i+':',slist.count(i))

"""5. Palindrome"""

def is_palindrome(s):
    if s==s[::-1]:   # reverses the string
        return True
    else:
        return False
s=input("Enter string: ")
is_palindrome(s)