# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Td1EvIQqCSaZeMmt3cvCP8CUg-Hm0TS
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_excel('heart_disease.xlsx', sheet_name=1, header=0)

df.head()

df.info()

df.shape

df.isnull().sum()

df['oldpeak'] = df['oldpeak'].fillna(df['oldpeak'].mean())

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.dtypes

df['cp'].value_counts()

df['trestbps'].value_counts()

df['sex'].value_counts()

df['fbs'].value_counts()

df['restecg'].value_counts()

df['slope'].value_counts()

df['thal'].value_counts()

from sklearn.preprocessing import LabelEncoder

label_encoder= LabelEncoder()

df['sex_encoded']=label_encoder.fit_transform(df['sex'])
sex_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
sex_mapping

df['thal_encoded']=label_encoder.fit_transform(df['thal'])
thal_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
thal_mapping

df['cp_encoded']=label_encoder.fit_transform(df['cp'])
cp_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
cp_mapping

df['fbs_encoded']=label_encoder.fit_transform(df['fbs'])
fbs_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
fbs_mapping

df['restecg_encoded']=label_encoder.fit_transform(df['restecg'])
restecg_mapping=dict(zip(label_encoder.classes_,range(len(label_encoder.classes_))))
restecg_mapping

df['slope_encoded']=label_encoder.fit_transform(df['slope'])
slope_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
slope_mapping

df['exang'].value_counts()

df['exang']=df['exang'].replace({'TURE':True, 'FALSE':False})

df['exang']=df['exang'].astype(bool)

df['exang'].value_counts()

df['exang_encoded']=label_encoder.fit_transform(df['exang'])
exang_mapping=dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
exang_mapping

columns_to_drop = ['sex','cp', 'fbs','thal','restecg','slope','exang']
df.drop(columns=columns_to_drop, inplace=True)

df.head()

sns.set_style('whitegrid')

num_features=len(df.columns)
num_rows=num_features // 4 + (num_features % 4 > 0)
plt.figure(figsize=(15,20))
df.hist(figsize=(20,15),bins=10,edgecolor='black',color='blue')
plt.suptitle('Histogram of numerical features', fontsize=15)
plt.tight_layout(rect=[0,0.03,1,0.95])
plt.show()

plt.figure(figsize=(15,10))
for i, column in enumerate(df.columns[:-1]):
  plt.subplot(3,4,i+1)
  plt.boxplot(df[column])
  plt.title(f'Boxplot of {column}')
plt.tight_layout()
plt.show()

correlation_matrix=df.corr()
plt.figure(figsize=(15,10))
plt.title('Correlation Matrix',fontsize=16)
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.tight_layout()
plt.show()

sns.pairplot(df,hue='num')

from math import isqrt
Q1=df['chol'].quantile(0.25)
Q3=df['chol'].quantile(0.75)
IQR=Q3-Q1
upper_bound=Q3+1.5*IQR
lower_bound=Q1-1.5*IQR
df=df[df['chol']>=lower_bound]
df=df[df['chol']<=upper_bound]
df['chol']=np.where(df['chol']>lower_bound,lower_bound, np.where(df['chol']<upper_bound,upper_bound,df['chol']))

plt.figure(figsize=(8,5))
sns.boxplot(x=df['trestbps'])
plt.title('Outlier detection using Boxplot',fontsize=15)
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

y=df['num']
y

x=df.drop(columns='num')
x

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

sc=StandardScaler()
X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

model=DecisionTreeClassifier(criterion = 'entropy',max_depth=5,random_state=48,min_samples_split=15)
model.fit(X_train_scaled,y_train)

plt.figure(figsize=(50,30))
plot_tree(model)
plt.title('Decision Tree')
plt.show()

fn=['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']
cn=['setosa', 'versicolor', 'virginica']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (32,18), dpi=300)

plot_tree(model, feature_names=x.columns, class_names=['0', '1','2','3','4'], filled=False)

pred=model.predict(X_test_scaled)
pred

pd.Series(pred).value_counts()

np.mean(pred==y_test)

accuracy = accuracy_score(y_test, pred)
print(f"Accuracy: {accuracy:.2f}")

report = classification_report(y_test, pred)
print("\nClassification Report:")
print(report)

model=DecisionTreeClassifier(criterion='gini',max_depth=5,random_state=77)

model.fit(X_train_scaled,y_train)
pred_gini=model.predict(X_test_scaled)
np.mean(pred_gini==y_test)

"""In Hyperparameter tuning i have removed outlier from chol column which helped me increase my Accuracy from 52% to 62%

I have experimented with different max_depth values like 3,4,5,6,7,8, the best results I get are at 3,4,5 . I also experimented with min_samples_split.

## 1. What are some common hyperparameters of decision tree models, and how do they affect the model's performance?

Decision tree models have several key hyperparameters that control their complexity and help prevent overfitting. Tuning these parameters is crucial for achieving good performance on unseen data.


* max_depth
This parameter sets the maximum number of levels allowed in the tree.

Effect on Performance: A smaller max_depth restricts the tree's complexity, which can prevent overfitting but may lead to underfitting if the model is too simple to capture the underlying patterns in the data. A larger max_depth allows the model to learn more specific and complex patterns, but it dramatically increases the risk of overfitting, where the model learns the noise in the training data.

* min_samples_split
This is the minimum number of data points required in a node before it can be split into two branches.

Effect on Performance: A higher value prevents the model from creating splits based on a small number of samples, thus making it more general and controlling overfitting. A very high value, however, can lead to underfitting. A lower value allows the tree to split on smaller groups, which can help capture finer details but increases the risk of overfitting.

* min_samples_leaf
This parameter specifies the minimum number of data points that must exist in a leaf node (a terminal node).

Effect on Performance: Similar to min_samples_split, a larger min_samples_leaf ensures that each final prediction is based on a substantial number of samples, which helps to smooth the model and avoid overfitting. A smaller value allows leaves to be created with very few samples, making the model more prone to learning noise and overfitting.

* max_features
This determines the number of features the model considers when looking for the best split at each node.

Effect on Performance: Limiting max_features introduces randomness and diversity, which can reduce the model's variance and help prevent overfitting, especially in ensemble methods like Random Forests. If the value is too small, it may lead to underfitting because the best possible split might be missed if the relevant feature isn't in the considered subset.

* criterion
This is the function used to measure the quality of a split. The two most common criteria are Gini Impurity and Entropy.

Criterion Options:

gini: Measures the probability of a randomly chosen sample being incorrectly classified. It's the default in many libraries like scikit-learn and is computationally faster.

entropy: Measures the level of disorder or randomness in a set of samples, based on information theory.

Effect on Performance: In practice, the choice between gini and entropy often has a minimal impact on the final accuracy of the tree. entropy can sometimes lead to slightly more balanced trees, but the difference is usually negligible

The main goal of tuning these hyperparameters is to find the right balance between model complexity and generalization, creating a model that performs well on both the training data and new, unseen data.

## 2. What is the difference between the Label encoding and One-hot encoding?

| Guideline           | Label Encoding                                                                            | One-Hot Encoding                                                                                   |
|:--------------------|:------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------|
| **Type of Data** |  Use for **Ordinal Data** where an inherent order exists (e.g., `Low` < `Medium` < `High`). | Use for **Nominal Data** where no order exists (e.g., `India`, `USA`, `Japan`).                 |
| **Model Compatibility**| Can be used safely with **tree-based models** (like Decision Trees, Random Forests).       | Essential for **linear models**, **distance-based models** (like KNN), and **neural networks**.    |
| **Main Consideration** | Introduces an artificial order which can mislead most models.                 | Can create very high dimensionality if the feature has many categories.                    |
"""