# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LzlUt6b2VcA5mo9s4PBPTkPDHbM12fth
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix,ConfusionMatrixDisplay
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

df=pd.read_csv('Zoo.csv')
df

df.head()

df.describe()

df.info()

df.isnull().sum()

plt.figure(figsize=(8,8))
sns.countplot(x='type',data=df)
plt.title('Type count of Zoo')
plt.show()

plt.figure(figsize=(8,8))
sns.boxplot(y='legs',data=df)
plt.title('Legs count of Zoo')
plt.show()

x=df.drop(columns=['animal name','type'])
y=df['type']

from numpy.random import RandomState
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

sc=StandardScaler()
x_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

param_grid = {'n_neighbors': np.arange(1, 16, 2),
              'metric': ['minkowski'],
              'p': [2]}
knn = KNeighborsClassifier()
gs  = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
gs.fit(x_scaled, y_train)

print(f'Best k: {gs.best_params_["n_neighbors"]}')
best_knn = gs.best_estimator_

y_pred = best_knn.predict(x_test_scaled)

print('\nAccuracy:', round(accuracy_score(y_test, y_pred), 3))
print('\nClassification report:\n', classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred, labels=best_knn.classes_)
ConfusionMatrixDisplay(cm, display_labels=best_knn.classes_).plot(cmap='Blues')
plt.title('Confusion matrix (test set)')
plt.show()

pca = PCA(n_components=2, random_state=42)
x_train_pca = pca.fit_transform(x_scaled)
x_test_pca  = pca.transform(x_test_scaled)

knn_2d = KNeighborsClassifier(n_neighbors=gs.best_params_["n_neighbors"])
knn_2d.fit(x_train_pca, y_train)

x_min, x_max = x_train_pca[:,0].min()-1, x_train_pca[:,0].max()+1
y_min, y_max = x_train_pca[:,1].min()-1, x_train_pca[:,1].max()+1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.05),
                     np.arange(y_min, y_max, 0.05))
Z = knn_2d.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

plt.figure(figsize=(8,6))
plt.contourf(xx, yy, Z, alpha=0.25)
scatter = plt.scatter(x_train_pca[:,0], x_train_pca[:,1],
                      c=y_train, edgecolor='k', marker='o', label='train')
plt.scatter(x_test_pca[:,0], x_test_pca[:,1],
            c=y_test, edgecolor='k', marker='^', label='test')
plt.legend(title='Animal type')
plt.title('KNN decision boundaries on first 2 PCA components')
plt.xlabel('PC 1'); plt.ylabel('PC 2')
plt.show()

df.isnull().sum()

df.fillna(df.median(numeric_only=True),inplace=True)

for col in df.select_dtypes(include='number').columns:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)
print(" Missing values handled and outliers capped.")

"""'''
##  What are the key hyperparameters in KNN?

| Hyperparameter     | Description                                                           |
|--------------------|------------------------------------------------------------------------|
| `n_neighbors`      | Number of nearest neighbors to consider for classification/regression |
| `weights`          | Uniform (equal weight) or distance-based weighting                    |
| `metric`           | Distance metric to use (e.g., Euclidean, Manhattan, Minkowski)         |
| `algorithm`        | Algorithm used to compute neighbors (auto, ball_tree, kd_tree, brute) |
| `leaf_size`        | Leaf size passed to BallTree or KDTree                                |

Choosing optimal `n_neighbors` and the right `metric` is key to improving model performance.
'''

'''
## What distance metrics can be used in KNN?

KNN supports several distance metrics. Common ones include:

- Euclidean Distance  
- Manhattan Distance
- Minkowski Distance  
- Hamming Distance
The choice of distance metric affects how neighbors are defined and ultimately impacts the classification accuracy.
'''
"""