# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SV_wNLQXVo9vkjnhfxbngVrIBKMYR2U7
"""

import pandas as pd
train = pd.read_csv("Titanic_train.csv")

print("Shape:", train.shape)
print(train.info())

print(train.describe(include="all"))
print(train.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x="Survived", data=train)
plt.title("Survival Count")
plt.show()

sns.countplot(x="Survived", hue="Sex", data=train)
plt.title("Survival by Gender")
plt.show()

sns.heatmap(train.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Fill missing values
train["Age"] = train["Age"].fillna(train["Age"].median())
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

# Encode categorical variables
le = LabelEncoder()
train["Sex"] = le.fit_transform(train["Sex"])
train["Embarked"] = le.fit_transform(train["Embarked"])

X = train[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]
y = train["Survived"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=35)

from sklearn.linear_model import LogisticRegression

# model
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

import pickle

# Save trained model to file
with open("titanic_model.pkl", "wb") as f:
    pickle.dump(model, f)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

# metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.plot(fpr, tpr, label="ROC Curve")
plt.plot([0,1], [0,1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# coefficients

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})
print(coefficients)

print("\nInterpretation:")
for f, c in zip(coefficients["Feature"], coefficients["Coefficient"]):
    if c > 0:
        print(f"{f}: increases chance of survival")
    else:
        print(f"{f}: decreases chance of survival")

import pandas as pd
import pickle
import ipywidgets as widgets
from IPython.display import display

# Load trained model
model = pickle.load(open("titanic_model.pkl", "rb"))

# Widgets
pclass = widgets.Dropdown(options=[1, 2, 3], description="Pclass:")
sex = widgets.Dropdown(options=["male", "female"], description="Sex:")
age = widgets.IntSlider(value=25, min=1, max=80, description="Age")
sibsp = widgets.IntSlider(value=0, min=0, max=10, description="SibSp")
parch = widgets.IntSlider(value=0, min=0, max=10, description="Parch")
fare = widgets.FloatSlider(value=30, min=0, max=600, step=1, description="Fare")
embarked = widgets.Dropdown(options=["C", "Q", "S"], description="Embarked:")
predict_button = widgets.Button(description="🔮 Predict")

output = widgets.Output()

def on_predict_clicked(b):
    # Encode inputs
    sex_val = 1 if sex.value == "male" else 0
    emb_map = {"C": 0, "Q": 1, "S": 2}
    emb_val = emb_map[embarked.value]

    features = pd.DataFrame([[pclass.value, sex_val, age.value, sibsp.value,
                              parch.value, fare.value, emb_val]],
                             columns=["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"])

    pred = model.predict(features)[0]

    with output:
        output.clear_output()
        if pred == 1:
            print("✅ The passenger would survive!")
        else:
            print("❌ The passenger would not survive.")

predict_button.on_click(on_predict_clicked)

# display
display(pclass, sex, age, sibsp, parch, fare, embarked, predict_button, output)

"""# Interview Questions
1. What is the difference between precision and recall?
Ans: Precision: Of the predicted positives, how many were actually positive.
     Recall: Of the actual positives, how many were correctly predicted.
2. What is cross-validation, and why is it important in binary classification?
Ans: Splitting data into parts, training on some, testing on others, and repeating.
     It avoids overfitting and gives a better estimate of how the model will perform on new data.
"""