# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133DUG1yaIOfUVQdmdatIpWtRxTzcLyWL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("ToyotaCorolla - MLR.csv")
df

df.head()

df.info()

df.describe()

df.shape

df.columns

df.dtypes

sns.pairplot(df)
plt.show()

"""* The relation between y and X should be high. The higher the value, the stronger the correlation
* The relation between any two independent variables should be low
 * if the correlation between any 2 independent variables is strong, then it is called a collinearity problem
"""

df.drop("Fuel_Type",axis=1).corr()

x=df.drop(columns="Price")
y=df["Price"]

"""we used drop because fuel_type was object for that we do correlation.

Train-Test Split
"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

x_train

from os.path import join
x_train_encoded=pd.get_dummies(x_train,columns=['Fuel_Type'],drop_first=True)
x_test_encoded=pd.get_dummies(x_test,columns=['Fuel_Type'],drop_first=True)

x_train_encoded,x_test_encoded=x_train_encoded.align(x_test_encoded,join='left',axis=1,fill_value=0)

x_train_encoded

"""Modelling

* Multiple Linear Regression—Linear regression includes multiple input features. This is done by least squares method
y = B₀ + B₁x₁ + ... Bₙxₙ

Each x represents a different feature, and each feature has its own coefficient
"""

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train_encoded,y_train)
print(model.intercept_)
print(model.coef_)

train_prediction=model.predict(x_train_encoded)
test_prediction=model.predict(x_test_encoded)

from sklearn.metrics import mean_squared_error
train_RSME=np.sqrt(mean_squared_error(y_train,train_prediction))
test_RSME=np.sqrt(mean_squared_error(y_test,test_prediction))
print(train_RSME)
print(test_RSME)

print(model.score(x_train_encoded,y_train))
print(model.score(x_test_encoded,y_test))

"""Lasso Regression

"""

from sklearn.linear_model import Lasso
Lasso_model=Lasso()
Lasso_model.fit(x_train_encoded,y_train)
print(Lasso_model.intercept_)
print(Lasso_model.coef_)

lasso_train_prediction=Lasso_model.predict(x_train_encoded)
lasso_test_prediction=Lasso_model.predict(x_test_encoded)

from sklearn.metrics import mean_squared_error
lasso_train_RSME=np.sqrt(mean_squared_error(lasso_train_prediction,y_train))
lasso_test_RSME=np.sqrt(mean_squared_error(lasso_test_prediction,y_test))
print(lasso_train_RSME)
print(lasso_test_RSME)
print(Lasso_model.score(x_train_encoded,y_train))
print(Lasso_model.score(x_test_encoded,y_test))

"""Ridge Regression

"""

from sklearn.linear_model import Ridge
ridge_model=Ridge()
ridge_model.fit(x_train_encoded,y_train)
print(ridge_model.intercept_)
print(ridge_model.coef_)

ridge_train_prediction=ridge_model.predict(x_train_encoded)
ridge_test_prediction=ridge_model.predict(x_test_encoded)

from sklearn.metrics import mean_squared_error
ridge_train_RSME=np.sqrt(mean_squared_error(ridge_train_prediction,y_train))
ridge_test_RSME=np.sqrt(mean_squared_error(ridge_test_prediction,y_test))
print(ridge_train_RSME)
print(ridge_test_RSME)

print(ridge_model.score(x_train_encoded,y_train))
print(ridge_model.score(x_test_encoded,y_test))

"""
#### What is Normalization & Standardization and how is it helpful?
Normalization is a data preprocessing technique used to rescale the values of numerical features so that they fall within a specific range, typically [0, 1]. It's especially important in machine learning and data analysis to ensure that all features contribute equally to the model’s learning

### Why Normalize?
Eliminates Bias: Features with larger ranges won't dominate those with smaller ranges.

Improves Model Performance: Algorithms like k-NN, SVM, and neural networks are sensitive to feature scales.

Speeds Up Convergence: Gradient descent converges faster when features are on a similar scale.

#### Standardization
##### What is Standardization?
Standardization is a data preprocessing technique that transforms features to have:

Mean = 0

Standard deviation = 1

This process is also called Z-score normalization.

### Why is Standardization Useful?

1. **Equal Feature Scaling**  
   Like normalization, it makes sure features with different units or scales (e.g., income vs age) contribute equally to the model.

2. **Works Well with Normally Distributed Data**  
   Some algorithms assume or perform better when the input features follow a normal (Gaussian) distribution. Standardization helps meet this assumption.

3. **Improves Model Performance**  
   Algorithms that are sensitive to feature distribution benefit from standardization:

   | Algorithm             | Needs Standardization? |
   |-----------------------|------------------------|
   | k-NN                  |    Yes                 |
   | SVM                   |    Yes                 |
   | Logistic Regression   |    Yes                 |
   | Linear Regression     |    Yes                 |
   | Neural Networks       |    Yes                 |
   | Decision Trees/Random Forests |  Not necessary |

4. **Faster Gradient Descent**  
   In models like linear regression or neural networks, standardization helps gradient descent converge faster by reducing zigzagging.
"""