# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUByqhr6-F8HdlIFhq4uiumar0pg1ftM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df=pd.read_excel('glass.xlsx',sheet_name='glass')

df.head()

df.describe()

df.info()

df.dtypes

df.isnull().sum()

df.hist(figsize=(15,10),bins=15)
plt.suptitle('Features Distributions')
plt.tight_layout()
plt.show()

from seaborn.palettes import color_palette
plt.figure(figsize=(15,10))
for i, col in enumerate(df.columns[:-1]):
    plt.subplot(3,4,i+1)
    sns.boxplot(y=df[col],color='lightblue')
    plt.xlabel(col)
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

sns.pairplot(df,hue='Type',palette='husl')
plt.suptitle('Pairwise Relationships',y=1.02)
plt.show()

correlation_matrix=df.corr()
plt.figure(figsize=(15,10))
sns.heatmap(correlation_matrix,annot=True,cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

x=df.drop('Type',axis=1)
y=df['Type']

sc=StandardScaler()
x_scaled=sc.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42,stratify=y)

rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

print("\nRandom Forest Results:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")

bagging=BaggingClassifier(estimator=RandomForestClassifier(n_estimators=50,random_state=42))
bagging.fit(x_train,y_train)
bagg_pred=bagging.predict(x_test)

print("\nBagging Results:")
print(confusion_matrix(y_test, bagg_pred))
print(classification_report(y_test, bagg_pred))
print(f"Accuracy: {accuracy_score(y_test, bagg_pred):.2f}")

boosting = AdaBoostClassifier(n_estimators=50, random_state=42)
boosting.fit(x_train, y_train)
y_boost = boosting.predict(x_test)

print("\nBoosting Results:")
print(classification_report(y_test, y_boost))
print(f"Accuracy: {accuracy_score(y_test, y_boost):.2f}")

"""### 1. Bagging vs Boosting

#### Bagging (Bootstrap Aggregating)

- **Goal**: Reduce variance and avoid overfitting.
- **Method**:
  - Create multiple subsets of the training data by sampling **with replacement**.
  - Train a **separate model** on each subset (usually decision trees).
  - Combine predictions by **averaging** (for regression) or **majority vote** (for classification).
- **Example Algorithms**:
  - Random Forest
  - Bagged Decision Trees

  #### Boosting

- **Goal**: Reduce bias and improve predictive accuracy.
- **Method**:
  - Build models **sequentially**.
  - Each new model focuses on **correcting the errors** made by the previous ones.
  - Assign more weight to misclassified points.
- **Example Algorithms**:
  - AdaBoost
  - Gradient Boosting Machines (GBM)
  - XGBoost, LightGBM, CatBoost

  
#### Key Differences

| Aspect         | Bagging                         | Boosting                        |
|----------------|----------------------------------|----------------------------------|
| Strategy       | Parallel                        | Sequential                      |
| Focus          | Reduce variance                 | Reduce bias                     |
| Data Sampling  | Bootstrap (random with replacement) | Weighted or full dataset      |
| Model Weights  | Equal                           | Weighted based on error        |
| Overfitting    | Helps avoid                     | Risk of overfitting if not tuned |
| Accuracy       | Stable improvement              | Higher accuracy (usually)       |

### 2. Handling Imbalanced Data

#### Problem:
- Imbalance occurs when one class significantly outweighs the other(s), e.g., 95% negative vs 5% positive.
- Leads to biased models that favor the majority class.

#### Techniques to Handle Imbalanced Data:

1. **Resampling Methods**:
   - **Oversampling** the minority class (e.g., SMOTE, Random Oversampling)
   - **Undersampling** the majority class
   - **Hybrid methods** (e.g., SMOTE + Tomek Links)

2. **Algorithmic Approaches**:
   - Use models that handle imbalance internally (e.g., `class_weight='balanced'` in Logistic Regression, SVM).
   - Tree-based models like XGBoost or LightGBM with `scale_pos_weight`.

3. **Evaluation Metrics**:
   - Avoid using only accuracy.
   - Use **Precision**, **Recall**, **F1 Score**, **ROC-AUC**, **Confusion Matrix**.

4. **Data Augmentation**:
   - In domains like NLP or image recognition, generate synthetic data for minority class.

5. **Ensemble Methods**:
   - Use balanced bagging, boosting, or cost-sensitive learning.
"""