# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PusTdq6UFxnKXQ0tTOX2nNWXcAkAuhdV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import  train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, ConfusionMatrixDisplay
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('mushroom.csv')
df

df.info()

df.head()

df.isnull().sum()

df.nunique()

df['class'].value_counts().plot(kind='bar', title='Class Distribution')

for col in ['odor','gill_color','spore_print_color']:
  plt.figure(figsize=(10,5))
  sns.countplot(x=col,hue='class', data=df)
  plt.title(f'{col} vs class')
  plt.show()

x=df.drop('class',axis=1)
y=df['class']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

pipe=Pipeline(steps=[('ohe', OneHotEncoder(handle_unknown='ignore')),
                     ('svc', SVC(kernel='rbf'))])
pipe.fit(x_train, y_train)
pipe_pred=pipe.predict(x_test)
print('\nAccuracy:', round(accuracy_score(y_test, pipe_pred), 3))
print('\nClassification report:\n', classification_report(y_test, pipe_pred))

cm=confusion_matrix(y_test,pipe_pred)
ConfusionMatrixDisplay(cm, display_labels=pipe.classes_).plot(cmap='Blues')
plt.title('Confusin matrix')
plt.show()

param_grid={ 'svc__kernel':['linear', 'rbf', 'poly']
             , 'svc__C':[0.1, 1, 10]
             , 'svc__gamma':['scale','auto']
           }
gs=GridSearchCV(pipe,param_grid=param_grid, cv=5,n_jobs=-1, scoring='f1',verbose=1)
gs.fit(x_train, y_train)
print(gs.best_params_)
print(gs.best_score_)

best=gs.best_estimator_
print(classification_report(y_test, best.predict(x_test)))
cm2=confusion_matrix(y_test,best.predict(x_test),labels=best.classes_)
ConfusionMatrixDisplay(cm2,display_labels=best.classes_).plot(cmap='Purples')
plt.title('Best model of Confusion Matrix')
plt.show()

kernels=['linear','rbf','poly']
results={}
for kernel in kernels:
  pipe=Pipeline(steps=[('ohe',OneHotEncoder(handle_unknown='ignore')),
                        ('svc',SVC(kernel=kernel))])
  pipe.fit(x_train, y_train)
  y_preds=pipe.predict(x_test)
  acc=accuracy_score(y_test,y_preds)
  results[kernel]=acc
  print(f"\nkernel:{kernel}")
  print("Acccuracy",round(acc,4))
  print(classification_report(y_test,y_preds))

plt.figure(figsize=(8,8))
plt.bar(results.keys(),results.values(),color=['lightgreen','salmon','Purple'])
plt.xlabel('Kernel')
plt.ylabel('Accuracy')
plt.ylim(0,1)
plt.title('Kernel vs Accuracy')
plt.grid(axis='y')
plt.show()