# -*- coding: utf-8 -*-
"""EDA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Rahman17309/ASSIGNMENT1/blob/main/EDA_2.ipynb

# ***`EDA 2`***

# Objective:
This assignment aims to equip you with practical skills in data preprocessing, feature engineering, and feature selection techniques, which are crucial for building efficient machine learning models. You will work with a provided dataset to apply various techniques such as scaling, encoding, and feature selection methods including isolation forest and PPS score analysis.

#Dataset:
Given "Adult" dataset, which predicts whether income exceeds $50K/yr based on census data.

# Tasks:
**1. Data Exploration and Preprocessing:**

•	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).

•	Handle missing values as per the best practices (imputation, removal, etc.).

•	Apply scaling techniques to numerical features:

•	Standard Scaling

•	Min-Max Scaling

•	Discuss the scenarios where each scaling technique is preferred and why.

**2. Encoding Techniques:**

•	Apply One-Hot Encoding to categorical variables with less than 5 categories.

•	Use Label Encoding for categorical variables with more than 5 categories.

•	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

**3. Feature Engineering:**

•	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.

•	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

**4. Feature Selection:**

•	Use the Isolation Forest algorithm to identify and remove outliers. Discuss how outliers can affect model performance.

•	Apply the PPS (Predictive Power Score) to find and discuss the relationships between features. Compare its findings with the correlation matrix.

# Data Exploration and Preprocessing:

Import necessary libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

"""Load the dataset"""

df = pd.read_csv('/content/adult_with_headers.csv')

"""Display basic information about the dataset"""

print("Dataset Information:")
df.info()

"""unique values"""

unique_values = df.nunique()
print("Number of unique values in each column:")
print(unique_values)

"""Summary statistics"""

print("\nSummary Statistics:")
df.describe()

"""Check for missing values"""

print("\nMissing Values:")
print(df.isnull().sum())

"""No missing values are found, If any found we can replace with mean, medain or we can remove"""

# Imputation - Replace missing values with mean
#df.fillna(df.mean(), inplace=True)

# Or Imputation - Replace missing values with median
# df.fillna(df.median(), inplace=True)

# Or Removal - Drop rows with missing values
# df.dropna(inplace=True)

"""Check data types"""

print("\nData Types:")
print(df.dtypes)

"""Check for duplicate values"""

print("\nDuplicate Values:")
print(df.duplicated().sum())

"""View duplicate values

"""

df[df.duplicated()]

"""Remove Duplicate values"""

df = df.drop_duplicates()

print("\nDuplicate Values:")
print(df.duplicated().sum())

"""No Duplicat Values are found

Apply Scaling Techniques to Numerical Features:
"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler

"""Select numerical features for scaling"""

numerical_features = df.select_dtypes(include=['float64', 'int64']).columns

"""Standard Scaling"""

scaler_standard = StandardScaler()
df[numerical_features] = scaler_standard.fit_transform(df[numerical_features])

"""Min-Max Scaling"""

scaler_minmax = MinMaxScaler()
df[numerical_features] = scaler_minmax.fit_transform(df[numerical_features])

"""### *•	Discuss the scenarios where each scaling technique is preferred and why.*

Discussion of scenarios where each scaling technique is preferred:

***Standard Scaling:***

**Scenario:**

Standard scaling (or Z-score normalization) is preferred when the distribution of the features is Gaussian-like (or approximately normally distributed).

**Reason:**

It centers the data around 0 with a standard deviation of 1, which makes it suitable for algorithms that assume zero-centered data, such as linear regression, logistic regression, and neural networks. It preserves the shape of the original distribution but standardizes the range of values.

***Min-Max Scaling:***

**Scenario:**

Min-max scaling is preferred when the distribution of the features is not Gaussian-like and the algorithm does not assume zero-centered data.

**Reason:**

It scales the data to a fixed range (usually 0 to 1), making it suitable for algorithms that require input features to be on the same scale, such as support vector machines (SVM), k-nearest neighbors (KNN), and neural networks with activation functions sensitive to scale, like sigmoid or tanh. Min-max scaling preserves the relative relationships between data points.

In summary, standard scaling is suitable for algorithms that assume zero-centered data and when the distribution is approximately Gaussian-like, while min-max scaling is more appropriate when the algorithm doesn't have such assumptions and requires input features to be within a specific range.

# Encoding Techniques:

•	Apply One-Hot Encoding to categorical variables with less than 5 categories

One-Hot Encoding for Columns with Less than 5 Categories:
"""

from sklearn.preprocessing import OneHotEncoder

# Initialize one-hot encoder
one_hot_encoder = OneHotEncoder(drop='first', sparse=False)

# Identify categorical columns with less than 5 categories
categorical_columns = df.select_dtypes(include=['object']).columns
columns_to_encode = [col for col in categorical_columns if df[col].nunique() < 5]

# Apply one-hot encoding to selected columns
for col in columns_to_encode:
    print(f"One-hot encoding column: {col}")
    encoded_features = one_hot_encoder.fit_transform(df[[col]])
    # Update column names with encoded feature names
    encoded_feature_names = [f"{col}_{cat}" for cat in one_hot_encoder.categories_[0][1:]]
    encoded_df = pd.DataFrame(encoded_features, columns=encoded_feature_names)
    # Drop original categorical column and concatenate encoded features
    df.drop(columns=[col], inplace=True)
    df = pd.concat([df, encoded_df], axis=1)

df.head()

"""•	Use Label Encoding for categorical variables with more than 5 categories.

Label Encoding for Columns with More than 5 Categories:
"""

from sklearn.preprocessing import LabelEncoder

# Initialize label encoder
label_encoder = LabelEncoder()

# Identify categorical columns with more than 5 categories
categorical_columns = df.select_dtypes(include=['object']).columns
columns_to_encode = [col for col in categorical_columns if df[col].nunique() >= 5]

# Apply label encoding to selected columns
for col in columns_to_encode:
    print(f"Label encoding column: {col}")
    df[col] = label_encoder.fit_transform(df[col])

df.head()

"""# Discussion of the pros and cons of One-Hot Encoding and Label Encoding:

**One-Hot Encoding:**

***Pros:***

Preserves Distinct Categories: One-hot encoding represents each category in a separate binary column, preserving the distinction between categories.
Suitable for Categorical Variables with Few Categories: It is suitable for categorical variables with a small number of unique categories.
Works well with Most Machine Learning Algorithms: One-hot encoding is compatible with most machine learning algorithms and does not impose assumptions about the relationship between categories.

***Cons:***

Increases Dimensionality: One-hot encoding increases the dimensionality of the dataset, especially when dealing with categorical variables with many unique categories, which can lead to the curse of dimensionality.
Sparse Representation: In datasets with many unique categories, the resulting one-hot encoded matrix can become sparse, consuming more memory and computational resources.
Introduces Multicollinearity: One-hot encoding introduces multicollinearity, as one category becomes perfectly predictable from the others. This can lead to issues in some algorithms like linear regression.

**Label Encoding:**

***Pros:***

Reduces Dimensionality: Label encoding reduces the dimensionality of the dataset by encoding categorical variables with integer labels, which can be beneficial for algorithms that struggle with high-dimensional data.
Preserves Order in Ordinal Variables: Label encoding preserves the ordinal relationship between categories if present in the data, which can be useful for certain algorithms.
Simpler Representation: The resulting encoded data is more compact compared to one-hot encoding, which can save memory and computational resources.

***Cons:***

Assumes Ordinal Relationship: Label encoding assumes an ordinal relationship between categories, which may not always be present or may not be correctly inferred by the algorithm.
May Introduce Unintended Order: Label encoding may introduce unintended ordinal relationships between categories, especially if the algorithm misinterprets the encoded integer labels as meaningful ordinal values.
Not Suitable for Nominal Variables: Label encoding is not suitable for categorical variables without an inherent order, as it may introduce spurious relationships between categories.


Overall, the choice between one-hot encoding and label encoding depends on the nature of the categorical variable, the specific requirements of the machine learning algorithm, and the potential trade-offs between dimensionality, interpretability, and computational efficiency.

# Feature Engineering:

•	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.

##Two new features that could be beneficial for the model, along with the rationale behind each choice:

##Income per Hour:
**Rationale:**

Calculating the income per hour can provide a normalized measure of an individual's earning efficiency, regardless of the number of hours worked. It helps capture the value generated per unit of time, which could be more informative than the absolute income or hours worked alone.

**Formula:** Income per Hour = (Income - Capital Loss) / Hours per Week

**Benefit:** This feature can help the model differentiate between individuals who earn higher incomes due to working longer hours versus those who earn higher incomes due to higher earning efficiency within a given timeframe.

##Total Capital Gain and Loss:

**Rationale:**
Combining capital gain and loss into a single feature can provide a holistic view of an individual's financial transactions and their net impact. It simplifies the representation of financial gains and losses, making it easier for the model to capture the overall financial behavior of individuals.

**Formula:** Total Capital Gain and Loss = Capital Gain - Capital Loss

**Benefit:** This feature captures the net financial gain or loss experienced by an individual, providing valuable information about their financial situation and investment behavior. It can help the model identify individuals with significant financial gains or losses, which may be indicative of their overall financial stability or risk-taking behavior.

Create a new feature: Income per Hour
"""

df['income_per_hour'] = (df['income_ >50K'] - df['capital_loss']) / df['hours_per_week']

"""Create a new feature: Total Capital Gain and Loss"""

df['total_capital_gain_loss'] = df['capital_gain'] - df['capital_loss']

df.head()

"""•	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

Check the skewness before transformation
"""

from scipy.stats import skew

# Select numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

# Calculate skewness for each numerical column
skewness = df[numerical_columns].apply(lambda x: skew(x.dropna()))

# Filter columns with right skewness (skewness > 0)
right_skewed_columns = skewness[skewness > 0].index

# Display columns with right skewness and their skewness values
for col in right_skewed_columns:
    print(f"Column '{col}' has skewness of {skewness[col]} (right skew)")

"""Based on the skewness values obtained, the 'capital_gain' feature has the highest skewness of approximately 11.95, indicating significant right skewness. This suggests that applying a transformation, such as a log transformation, to the 'capital_gain' feature would likely be the most suitable choice."""

import plotly.express as px

# Calculate skewness for each numerical column
skewness = df[numerical_columns].apply(lambda x: skew(x.dropna()))

# Filter columns with right skewness (skewness > 0)
right_skewed_columns = skewness[skewness > 0].index

# Create a DataFrame for plotting
skewness_df = pd.DataFrame({'Column': right_skewed_columns, 'Skewness': skewness[right_skewed_columns]})

# Create an interactive bar plot
fig = px.bar(skewness_df, x='Column', y='Skewness',
             title='Skewness of Numerical Columns (Right Skewed)',
             labels={'Skewness': 'Skewness'},
             color='Skewness',
             color_continuous_scale='RdYlBu')

# Update layout for better visualization
fig.update_layout(xaxis_title='Column', yaxis_title='Skewness',
                  coloraxis_colorbar=dict(title='Skewness'))

fig.show()

original_skewness = df['capital_gain'].skew()
print("Original Skewness of 'capital_gain':", original_skewness)

"""Apply log transformation to 'capital_gain'"""

df['capital_gain_log'] = np.log1p(df['capital_gain'])

"""Check the skewness of 'capital_gain' after transformation"""

transformed_skewness = df['capital_gain_log'].skew()
print("Skewness of 'capital_gain' after Log Transformation:", transformed_skewness)

"""After applying a log transformation to 'capital_gain', the skewness reduces to approximately 10.67.

##Justification for Log Transformation:

Log transformation is effective for reducing skewness in highly skewed distributions like financial data.

It preserves relative differences between lower values while compressing larger values, making it suitable for financial data analysis.

Log transformation helps in normalizing the distribution, making the data more suitable for modeling techniques.

# Feature Selection:

•	Use the Isolation Forest algorithm to identify and remove outliers. Discuss how outliers can affect model performance.

Check for infinite or extremely large values
"""

import plotly.express as px

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

fig = px.box(df, y=numerical_columns, title='Box plot of Numerical Columns')
fig.update_layout(xaxis_title='Column', yaxis_title='Value', yaxis=dict(type='linear'))
fig.show()

print("Number of infinite or extremely large values in the dataset:")
print(df[~np.isfinite(df).all(axis=1)].shape[0])

"""Replace infinite or extremely large values with NaN"""

df.replace([np.inf, -np.inf], np.nan, inplace=True)

"""Remove rows containing NaN values"""

df.dropna(inplace=True)

"""Initialize the Isolation Forest model"""

from sklearn.ensemble import IsolationForest

iso_forest = IsolationForest(contamination=0.05, random_state=42)

"""Fit the model and predict outliers"""

outlier_preds = iso_forest.fit_predict(df)

"""Filter out non-outliers"""

df_no_outliers = df[outlier_preds == 1]

"""Display the shape of the dataset before and after removing outliers"""

print("Shape of dataset before removing outliers:", df.shape)
print("Shape of dataset after removing outliers:", df_no_outliers.shape)

"""Visualization of outliers before and after applying isolation forest"""

# Define numerical columns for visualization
numerical_columns = ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

# Sample a subset of the data
sample_size = 1000
df_sample = df.sample(sample_size, random_state=42)
df_no_outliers_sample = df_no_outliers.sample(sample_size, random_state=42)

# Concatenate the original DataFrame with the one without outliers
df_concat_sample = pd.concat([df_sample[numerical_columns], df_no_outliers_sample[numerical_columns]], keys=['Before Outlier Removal', 'After Outlier Removal'])

# Create pair plot
sns.pairplot(df_concat_sample.reset_index(level=0), hue='level_0', diag_kind='kde', markers=['o', 's'])
plt.suptitle('Pair Plot Before and After Outlier Removal (Sampled Data)')
plt.show()

"""# Discuss how outliers can affect model performance.

**Skewing Results:** Outliers can distort statistical measures like mean and standard deviation, leading to biased model predictions.

**Decreased Accuracy:** Outliers can introduce noise in the data, reducing the accuracy of the model's predictions.

**Model Instability:** Outliers can influence the model's decision boundaries, leading to unstable and unreliable predictions.

**Overfitting:** Models may overfit to outliers, capturing noise instead of the underlying patterns in the data, resulting in poor generalization to new data.

**Misleading Relationships:** Outliers can create misleading relationships between variables, leading to erroneous conclusions and model interpretations.

Overall, removing outliers is essential to ensure the reliability and accuracy of machine learning models.

•	Apply the PPS (Predictive Power Score) to find and discuss the relationships between features. Compare its findings with the correlation matrix.

Calculate the Predictive Power Score (PPS) matrix
"""

!pip install ppscore

# Calculate the Predictive Power Score (PPS) matrix
pps_matrix = pps.matrix(df)

# Display the PPS matrix
print("Predictive Power Score (PPS) Matrix:")
print(pps_matrix)

"""Reshape the PPS matrix values"""

num_rows = len(pps_matrix["x"].unique())
num_cols = len(pps_matrix["y"].unique())
pps_values_reshaped = pps_matrix.ppscore.values.reshape(num_rows, num_cols)

"""Create heatmap for the PPS matrix"""

import plotly.graph_objects as go

fig = go.Figure(data=go.Heatmap(z=pps_values_reshaped,
                                x=pps_matrix["y"].unique(),
                                y=pps_matrix["x"].unique(),
                                colorscale='Viridis'))

# Customize the layout
fig.update_layout(title='Predictive Power Score (PPS) Matrix',
                  xaxis_title='Features',
                  yaxis_title='Features')

# Show the interactive plot
fig.show()

"""Compare with the correlation matrix"""

correlation_matrix = df.corr()

# Display the correlation matrix
print("\nCorrelation Matrix:")
print(correlation_matrix)

"""Visualize the correlation matrix"""

plt.figure(figsize=(13, 12))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")

plt.title('Comparison of PPS Matrix and Correlation Matrix')
plt.show()

"""#Based on the Predictive Power Score (PPS) matrix and the correlation matrix:

#PPS Matrix Insights:

The PPS matrix provides information about the predictive power of each feature with respect to others.

A PPS score of 1.0 indicates that the feature perfectly predicts itself (predict_itself case).

A PPS score of 0.0 suggests that there is no predictive power between the two features (regression case).

The PPS matrix also includes information about the model used and scores related to the model's performance.

#Correlation Matrix Insights:

The correlation matrix shows the linear relationship between pairs of features.

Correlation coefficients range from -1 to 1, where 1 indicates a perfect positive linear relationship, -1 indicates a perfect negative linear relationship, and 0 indicates no linear relationship.

However, correlation only measures linear relationships and may not capture non-linear associations.

#Comparison:

Both matrices provide valuable insights into the relationships between features, but they measure different aspects.

The PPS matrix captures non-linear relationships and provides additional information about predictive power beyond linear associations.

On the other hand, the correlation matrix only measures linear relationships and may overlook non-linear associations.

Comparing the two matrices can help identify discrepancies and provide a more comprehensive understanding of feature relationships.

Overall, by analyzing both the PPS matrix and the correlation matrix, we can gain a deeper understanding of the relationships between features and make more informed decisions in model building and feature selection.
"""