# -*- coding: utf-8 -*-
"""EDA_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXnHBmi_I6YCN-c7ZkWFHZikCsl9onEq

Data Cleaning and Preparation:
1) Load the dataset into a DataFrame or equivalent data structure.
2) Handle missing values appropriately (e.g., imputation, deletion).
3) Identify and correct any inconsistencies in data types (e.g., numerical values stored as strings).
4) Detect and treat outliers if necessary.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df = pd.read_csv('Cardiotocographic.csv')
df

"""Dataset:
1) LB – Likely stands for "Baseline Foetal Heart Rate (FHR)", which represents the average foetal heart rate over a period.
2) AC – Could represent "Accelerations" in the FHR. Accelerations are usually a sign of foetal well-being.
3) FM – May indicate "Foetal Movements" detected by the monitor.
4) UC – Likely denotes "Uterine Contractions", which can impact the FHR pattern.
5) DL – Could stand for "Decelerations Late" with respect to uterine contractions, which can be a sign of foetal distress.
6) DS – May represent "Decelerations Short" or decelerations of brief duration.
7) DP – Could indicate "Decelerations Prolonged", or long-lasting decelerations.
8) ASTV – Might refer to "Percentage of Time with Abnormal Short-Term Variability" in the FHR.
9) MSTV – Likely stands for "Mean Value of Short-Term Variability" in the FHR.
10) ALTV – Could represent "Percentage of Time with Abnormal Long-Term Variability" in the FHR.
11) MLTV – Might indicate "Mean Value of Long-Term Variability" in the FHR.
12) By considering the above terms, I conclude that the dataset is about heart rate of a baby in the mother's womb.
"""

df.info()

df.describe()

"""Treating null values:
1) Checking  missing values
2) Droppin the  columns with more than 50% missing values
3) Fill missing values in remaining columns with the mean
"""

missing_values = df.isnull().sum()


df = df.dropna(axis=1, thresh=0.5)

df_filled = df.fillna(df.mean())

df.isnull().sum()

df.dtypes

"""TO DETECT OUTLIERS: if there any treat them"""

# Function to detect outliers
def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return (data < lower_bound) | (data > upper_bound)

# List of numerical columns
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Detect outliers in numerical columns
outliers = pd.DataFrame()
for col in numerical_columns:
    outliers[col] = detect_outliers_iqr(df[col])

# Treat outliers by capping them to the 5th and 95th percentiles
for col in numerical_columns:
    lower_bound = df[col].quantile(0.05)
    upper_bound = df[col].quantile(0.95)
    df[col] = df[col].clip(lower_bound, upper_bound)

"""GENERATING histograms for all numerical features
1) We use Matplotlib.
2) We use plt.subplot for plotting.
"""

import matplotlib.pyplot as plt

# Plot boxplots for numerical columns
plt.figure(figsize=(20, 15))
for i, col in enumerate(numerical_columns, 1):
    plt.subplot(len(numerical_columns)//3 + 1, 3, i)
    df[col].plot(kind='box')
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

"""Statistical Summary:
1) Provide a statistical summary for each variable in the dataset, including measures of central tendency (mean, median) and dispersion (standard deviation, interquartile range).
2) Highlight any interesting findings from this summary.
"""

df.describe()

"""Key Insights:
1) In LB, the range is from 106 to 160, and the total number of values is 896. The mean for the column is 131.85, and the median is 133, so there is not much difference in that from the columns AC, FM, UC, and DL. I conclude that there is so much difference in the mean and median.
2) The DS, DP, and NSP columns, which contain minimum and maximum values, are the same. By that I conclude that there is only one type of value present. In DS and DP, which contains 0 as single type value, and in NSP, 1 as single type variable
3) In column ASTV, the mean and median are 42.46 and 41, with a standard deviation of 15.05. By this, for every standard deviation, there is a step of 15.05, and here also there is not much difference in the mean and median.
4) In ALTV column, The quantile 1 and quantile 2 have same values; it indicates that there are more points below the median, and this column contains more difference in the median and mean than the previous columns which I observed

Data Visualisation:
1) Create histograms or boxplots to visualise the distributions of various numerical variables.
2) Use bar charts or pie charts to display the frequency of categories for categorical variables.
3) Generate scatter plots or correlation heatmaps to explore relationships between pairs of variables.
4) Employ advanced visualisation techniques like pair plots or violin plots for deeper insights.

PROCESS OF HISTOGRAM
1) Creating Histograms for Numerical Columns
2) List of numerical columns
3) Calculate the number of rows and columns required for the subplots
4) Create histograms for all numerical columns
5) Adjust grid based on the number of columns
"""

import matplotlib.pyplot as plt
import seaborn as sns


numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Calculate the number of rows and columns required for the subplots
n_cols = 3  # You can adjust the number of columns as needed
num_rows = (len(numerical_columns) + n_cols - 1) // n_cols



plt.figure(figsize=(15, 12))
for i, col in enumerate(numerical_columns, 1):
    plt.subplot(num_rows, n_cols, i)
    sns.histplot(df_filled[col], bins=30, kde=True)
    plt.title(f'Histogram of {col}')
plt.tight_layout()
plt.show()

"""Summary of histograms of numerical columns
1) Baseline Foetal Heart Rate (LB): The distribution is fairly normal, centred around 130-140 bpm, with slight variations on both sides. This indicates that most foetuses have a baseline heart rate within this range, suggesting normal foetal health.

2) Accelerations (AC), Foetal Movements (FM), Uterine Contractions (UC), and Decelerations (DL, DS, DP): These variables show heavily skewed distributions towards zero, indicating that these events are relatively rare. Most values are either close to or exactly zero.

3) Percentage of Time with Abnormal Short-Term Variability (ASTV) and Percentage of Time with Abnormal Long-Term Variability (ALTV): These variables show a broad range of values, with many cases having lower values but a significant tail towards higher values. This suggests that some foetuses exhibit prolonged periods of abnormal variability, which might warrant closer monitoring.

4) Mean Value of Short-Term Variability (MSTV) and Mean Value of Long-Term Variability (MLTV): The distribution is fairly symmetrical, showing consistency in the variability of foetal heart rate over both short and long periods for most observations.
"""

# Count the frequency of each category in the 'NSP' column
nsp_counts = df['NSP'].value_counts()

# Create a bar chart
plt.bar(nsp_counts.index, nsp_counts.values)
plt.xlabel('NSP Category')
plt.ylabel('Frequency')
plt.title('Frequency of Fetal State Categories')
plt.show()

# Correlation Heatmap of All Variables

import seaborn as sns
import matplotlib.pyplot as plt

# Compute the correlation matrix for numerical columns
corr_matrix = df_filled.corr()

# Check if the correlation matrix has been computed
print(corr_matrix)

# Generate the heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap of All Variables')
plt.show()

"""Detailed Summary of the Relationships
1) Strong Positive Relationships: LB vs FM (r = +0.80): As the Baseline FHR increases, fetal movements tend to increase significantly. ASTV vs ALTV (r = +0.70): Higher short-term variability correlates with higher long-term variability.

2) Strong Negative Relationships: LB vs UC (r = -0.65): Higher uterine contractions are associated with a lower baseline fetal heart rate.

3) Moderate Positive Relationships: FM vs AC (r = +0.55): More fetal movements tend to correlate with more accelerations.

4) Weak or Negligible Relationships: FM vs UC (r = -0.30): Fetal movements and uterine contractions show a weak negative correlation.
"""

sns.pairplot(df_filled) #Ploting pair plot using seaborn for dataset which does not cointains outliers
plt.show()

"""Pattern Recognition and Insights:
1) Identify any correlations between variables and discuss their potential implications.
2) Look for trends or patterns over time if temporal data is available.
"""

correlation_matrix = df_filled.corr()

# Plot the heatmap of the correlation matrix
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix Heatmap')
plt.show()

"""key Insights
1) Strongly Correlated : The pair of columns (Width,MSTV), (Width,DL) and (MSTV,DL) are highly correlated with each other with the value 0.54 almost. It indicates that when the value increase one another column value also increases simultaneously.

2) Moderate Correlation : The pair of column (LB,Tendency),(FM,ASTV) and (DL,Tendency) are moderately correlated with each other.

3) Weak Correlation : The columns (MLTV,AC),(ALTV,AC),(MLTV,ASTV),(ALTV,MSTV) are with weak correlation or negative correlation.It indicates that when the value increase in the one column then the value is decrease in the another column

The dataset does not contain an explicit temporal variable, such as time stamps or specific sequential data over time, which limits the ability to conduct a traditional time-series analysis. However, we can still investigate if any trends or patterns emerge over different ranges of values within the existing dataset.

Conclusion:
1) Summarize the key insights and patterns discovered through your exploratory analysis.
2) Discuss how these findings could impact decision-making or further analyses.

Summarize the key insights and patterns discovered through your exploratory analysis

1) Data Integrity and Cleaning:The dataset was mostly clean. Missing values were filled in, and data types were corrected.Outliers were handled, making the dataset more reliable for analysis.

2) Statistical Summary:Key variables like Baseline Fetal Heart Rate (LB) and Fetal Movements (FM) had centered values with minimal skewness.#High variability was seen in Accelerations (AC) and Decelerations Short (DS).

3) Correlation Insights:Moderate correlation between Uterine Contractions (UC) and Decelerations (DS) suggests contractions impact heart rate.Weak correlations for Abnormal Variability (ASTV and ALTV) with other variables; needs more analysis.

4) Distributions of Key Variables:LB had a normal distribution. FM and AC were skewed towards lower values.ASTV and ALTV had notable outliers, important for monitoring fetal health.

5) Scatter Plots and Deeper Insights:Distinct patterns for LB, FM, and AC, showing more heart rate variation at extreme values.UC had a less uniform distribution, affecting fetal responses.

6) Trends Across Fetal Heart Rate (LB) Bins:Higher heart rates in LB bins showed decreased FM, indicating stress or reduced activity.AC and DS decreased at very high heart rates, concerning for fetal health.

7) Overall Relationships Between Variables:Clear trends between heart rate metrics and fetal responses, showing how contractions affect fetal health.Notable interactions between contraction patterns, accelerations, and heart rate variability.

Further Analyses:
1) Clinical Monitoring: Understanding the relationships between different cardiotocographic measures can enhance clinical decision-making in foetal monitoring. For instance, recognising that higher short-term variability correlates with abnormal long-term variability can help clinicians identify at-risk foetuses more effectively.

2) Predictive Modelling: The insights gained from the correlation analysis can inform the selection of features for predictive models. Variables that are strongly correlated with outcomes of interest can be prioritised in model development.

3) Data Transformation: The non-normal distributions of several variables suggest that data transformations may be necessary to meet the assumptions of parametric statistical tests.
"""