# -*- coding: utf-8 -*-
"""Basic_stats_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqQjrApRu3dlkPSEmNZg_PC-ElGuaVMs

Data:
A total of 15 print-heads were randomly selected and tested until failure. The durability of each print-head (in millions of characters) was recorded as follows:
(1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29)
"""

import numpy as np
from scipy import stats   #imported libraries

ph=[1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]
ph          #given data is listed

sample_mean=np.mean(ph)
sample_mean                    #sample mean of the list is calculated

sample_size=len(ph)

"""a. Build 99% Confidence Interval Using Sample Standard Deviation
Assuming the sample is representative of the population, construct a 99% confidence interval for the mean number of characters printed before the print-head fails using the sample standard deviation. Explain the steps you take and the rationale behind using the t-distribution for this task.
"""

sample_std=np.std(ph,ddof=1)     #sample std of the list is calculated
sample_std                       #ddof=delta degree of freedom(list size-1)

t_value=stats.t.ppf(0.995,df=sample_size-1)    #t-critical value is calculated
t_value

moe=t_value*(sample_std/np.sqrt(sample_size))
moe                                             #margin of error is calculated

con_int=(sample_mean-moe,sample_mean+moe)
con_int                                      #confident intervals using sample standard deviation are calculated

"""Explanation: Given the small sample size (\(n < 30\)), it is more appropriate to use the t-distribution for constructing the confidence interval. This choice is particularly suitable because the population standard deviation is unknown. By using the sample standard deviation in conjunction with the t-distribution, we can account for this uncertainty. The t-distribution is defined by the degrees of freedom (\(n - 1\)), which adjusts for the sample size and provides a more accurate estimate for small samples. This ensures a more reliable confidence interval for the mean number of characters printed before the printhead fails.

b. Build 99% Confidence Interval Using Known Population Standard Deviation
If it were known that the population standard deviation is 0.2 million characters, construct a 99% confidence interval for the mean number of characters printed before failure.
"""

popu_std=0.2 #population standard deviation

z_value=stats.norm.ppf(0.995)             #z-critical value is calculated
z_value

mone=z_value*(popu_std/np.sqrt(sample_size))
mone                                              #margin of error using population standard deviation is calculated

conf_int=(sample_mean-mone,sample_mean+mone)
conf_int                                          #confident intervals using population standard deviation are calculated

"""Explanation: We use the z-distribution when the population standard deviation is known and the sample size is large (typically n > 30). The z-distribution is a standardised form of the normal distribution with a mean of 0 and standard deviation of 1. A 99% confidence interval is constructed using the sample mean, the z-value corresponding to the desired confidence level, and the standard error. This interval estimates the range within which the true population mean is likely to fall with 99% confidence.

Conclusion: Two 99% confidence intervals were calculated for the mean number of characters printed before failure:

Using the sample standard deviation, the interval is (1.087, 1.389) million characters and using the known population standard deviation of 0.2 million characters, the interval is (1.105, 1.371) million characters. Both intervals suggest that we can be 99% confident the true average durability of the printheads lies within these ranges. These results are valuable for the manufacturer to assess product reliability, maintain quality standards, and inform production decisions.
"""