# -*- coding: utf-8 -*-
"""Basic_Stats_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pR_edm203cG7-XQznCsMvC0lalv_BHJX
"""

pip install numpy #numpy library installed

pip install pandas #pandas library imdtalled

import numpy as np
import pandas as pd

df=pd.read_csv("sales_data_with_discounts.csv")
df                         #The dataset is imported using pd.read_csv()

df.dtypes #datatypes of df

numerical_columns = df.select_dtypes(include=[np.number]) # all numerical columns are selected

numerical_columns.columns.tolist() #numerical columns list is created

numerical_columns.dtypes #datatypes of numerical columns

numerical_columns

df['Volume'].mean()

df['Volume'].median()

df['Volume'].std()

df['Volume'].mode()

df['Avg Price'].mean()

df['Avg Price'].median()

df['Avg Price'].mode()

df['Avg Price'].std()

df['Total Sales Value'].mean()

df['Total Sales Value'].median()

df['Total Sales Value'].mode()

df['Total Sales Value'].std()

df['Discount Rate (%)'].mean()

df['Discount Rate (%)'].median()

df['Discount Rate (%)'].std()

df['Discount Rate (%)'].mode()

df['Discount Amount'].mean()

df['Discount Amount'].median()

df['Discount Amount'].std()

df['Discount Amount'].mode()

df['Net Sales Value'].mean()

df['Net Sales Value'].std()

df['Net Sales Value'].median()

df['Net Sales Value'].mode()

"""The above single codes depicts the values of mean, median, mode and standard deviation"""

stats = {}

for col in numerical_columns:
    stats[col] = {
        'mean': df[col].mean(),
        'median': df[col].median(),
        'mode': df[col].mode()[0],
        'std_dev': df[col].std()
    }

stats_df = pd.DataFrame(stats)
stats_df

"""The dataframe is created of numerical columns stats"""

cat_columns = df.select_dtypes(include=['object', 'category']).columns

cat_columns

"""In the above code the categorical columns are selected and printed"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

# %matplotlib inline

"""%matplotlib is used for good padding or layout"""

numerical_columns.hist(figsize=(12, 8), bins=20)
plt.tight_layout()
plt.show()

"""Plots distribution for each numerical column.
Identifies distribution shape, skewness, and possible outliers.
Right- or left-skewed distributions.
Some variables may be normally distributed.
Sales data may have long tails or clustering.
"""

import seaborn as sns

plt.figure(figsize=(800, 6))
for i, col in enumerate(numerical_columns):
    plt.subplot(1, len(numerical_columns), i+1)
    sns.boxplot(y=df[col])
    plt.title(col)
plt.tight_layout()
plt.show()

"""Shows interquartile range and highlights outliers.
Detect outliers and spread of data.
Variables with outliers identified.
Helps decide if preprocessing like transformation or outlier removal is needed.
"""

for col in cat_columns:
  df[col].value_counts().plot(kind='bar',title=col)
  plt.show()

"""Plots the frequency of each category in categorical columns. Understands class distribution and dominance.Identifies the most common regions/products and also may help in targeting segments."""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standardized = df.copy()
df_standardized[numerical_columns.columns] = scaler.fit_transform(df[numerical_columns.columns])

"""Scales all numerical features to have a mean of 0 and std of 1 using Z = (x - μ)/σ. Removes scale bias before ML models (e.g., distance-based models).
All features brought to a uniform scale.Distributions are now centred at 0.
"""

import matplotlib.pyplot as plt

df[numerical_columns.columns].hist(figsize=(10, 8), bins=20)
plt.suptitle("Before Standardization")
plt.show()

df_standardized[numerical_columns.columns].hist(figsize=(10, 8), bins=20)
plt.suptitle("After Standardization")
plt.show()

"""Converts categorical variables into binary columns.E.g., a place with 3 values becomes place_A, place_B, and place_C.Prepares categorical data for machine learning models that require numerical input then dataset becomes fully numeric and increases dimensionality but makes data ML-ready."""

df_encoded = pd.get_dummies(df, columns=cat_columns)
print(df_encoded.head())

"""Transformed categorical variables into a format that can be provided to ML algorithms for future predictions

Conclusion:
Descriptive stats show sales, discounts, and volumes vary widely. Visualizations revealed sales peaks and discount patterns by brand and city and some products and cities consistently perform better.

Importance of preprocessing:
Standardization scales numbers equally so no feature dominates.
One-hot encoding converts categories to numbers for models.Both steps prepare data for accurate and good machine learning.
"""